### ISSUE TITLE
Not working: Error message on load: "MathJax is not defined"

### ISSUE THREAD

**Issue by markbao** [wonglkd/mathflowy#1] opened 2016-03-24 18:26 UTC
Getting this error message, on load, while loading Workflowy:

```
Uncaught ReferenceError: MathJax is not defined

refreshVisibleChildrenUnderSelectedForAddButton @ render.js:70constructProjectTreeAsSelected @ document_view.js?v=20160322190640:369Class.extend.constructProjectTreeAsSelected @ document_view.js?v=20160322190640:390selectProjectReferenceInstantly @ document_view.js?v=20160322190640:114selectAndSearchUsingLocation @ document_view.js?v=20160322190640:102documentReadyFunc @ document_view.js?v=20160322190640:87documentReadyFunc @ render.js:48k @ document_view.js?v=20160322190640:84r.success @ document_view.js?v=20160322190640:708f.resolveWith @ jquery-1.5.1.min.js:16v @ jquery-1.5.1.min.js:16c @ jquery-1.5.1.min.js:16
```

Seems like MathJax is being called before it is loaded.

Chrome Version 49

**Comment by wonglkd** [comment] 2016-04-13 21:31
Sorry for the slow response! I didn't get the error and I'm using Chrome 49 as well. Any steps to reproduce the bug?

**Comment by wonglkd** [comment] 2016-09-22 08:36
Closing since I can't reproduce this. Please feel free to reopen it if you can provide me with some steps to reproduce the issue!

**Closed as completed by wonglkd** 2016-09-22 08:36 UTC
